ifdef CONFIG_KCOV
CFLAGS_KCOV	:= $(call cc-option,-fsanitize-coverage=trace-pc,)
CFLAGS_KCOV += $(call cc-option,-fsanitize-coverage=no-prune,)
ifeq ($(CONFIG_KCOV_ENABLE_COMPARISONS),y)
CFLAGS_KCOV += $(call cc-option,-fsanitize-coverage=trace-cmp,)
endif

endif
